branch_whitelist = ["master"]
from_latest_tag = true
tag_prefix = "v"

pre_bump_hooks = [
  "sh ./scripts/check-header.sh",
  "sh ./scripts/bump-version.sh {{version}}",
  "cargo check",
]

post_bump_hooks = [
  "git push origin master",
  "git push origin {{version_tag}}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
owner = "ailuracollective"
repository = "colander"
authors = [{ signature = "psgf.tech+github@gmail.com", username = "SiddharthaGF" }]