#ifndef COLANDER_H
#define COLANDER_H

#pragma once

/* Generated by cbindgen from colander - do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
/*
 * colander: the form core, C ABI v1.
 *
 * Every function takes one NUL-terminated UTF-8 JSON request string (or NULL)
 * and returns a NUL-terminated UTF-8 JSON envelope owned by the caller. Release
 * it with colander_free_string(); it must never be passed to free().
 *
 *   success: {"ok":true,"result":{...}}
 *   failure: {"ok":false,"error":{"kind":"invalid_request|validation|panic",
 *                                 "message":"..."}}
 *
 * A NULL, non-UTF-8 or non-object request yields kind "invalid_request"; a
 * payload the core rejects yields "validation"; a contained Rust panic yields
 * "panic". No function ever unwinds into the caller, and no function returns
 * NULL.
 *
 * Requests (all keys are camelCase):
 *
 *   colander_compile
 *     {"formSchemaJson":"<json>","uiSchemaJson":"<json>|null",
 *      "rulesSchemaJson":"<json>|null",
 *      "components":[{"code":"...","version":"1.0.0",
 *                     "formSchemaJson":"<json>",
 *                     "uiSchemaJson":"<json>|null",
 *                     "contentHash":"<hex>|null"}]}
 *     -> {"formSchemaJson":"<json>","uiSchemaJson":"<json>|null",
 *         "rulesSchemaJson":"<json>|null",
 *         "dependencyMetadataJson":"<json>","contentHash":"<hex>"}
 *
 *   colander_evaluate_rules
 *     {"formSchemaJson":"<json>","rulesSchemaJson":"<json>",
 *      "uiSchemaJson":"<json>|null","values":{...}}
 *     -> {"visibility":{},"enabled":{},"required":{},
 *         "calculatedValues":{},"validationErrors":[{"code","message"}]}
 *
 *   colander_validate_response
 *     {"formSchemaJson":"<json>","uiSchemaJson":"<json>|null",
 *      "rulesSchemaJson":"<json>|null","answersJson":"<json>",
 *      "mode":"Draft"|"Complete"}
 *     -> {"normalizedAnswersJson":"<json>",
 *         "errors":[{"code","path","message"}],"isValid":bool}
 *
 *   colander_validate_schema
 *     colander ships no schemas: "schemas" carries the JSON Schema text for the
 *     document kinds the call validates, and is required for each kind used.
 *
 *     {"kind":"form"|"component"|"workflow","formSchemaJson":"<json>",
 *      "uiSchemaJson":"<json>|null","rulesSchemaJson":"<json>|null",
 *      "workflowSchemaJson":"<json>","published":bool,
 *      "schemas":{"formSchema":"<json schema>","uiSchema":"<json schema>",
 *                 "rulesSchema":"<json schema>","workflowSchema":"<json schema>"}}
 *     -> {"valid":true}
 *
 *     The domain-free entry point validates any instance against any schema:
 *     {"kind":"instance","schemaJson":"<json schema>","instanceJson":"<json>",
 *      "label":"instance"}  -> {"valid":true}
 *
 *   colander_content_hash
 *     {"formSchemaJson":"<json>","uiSchemaJson":"<json>|null",
 *      "rulesSchemaJson":"<json>|null"}
 *     -> {"contentHash":"<sha256 hex>"}
 *
 *   colander_next_version
 *     {"published":["1.0.0", ...]}  -> {"next":"1.0.1"}
 *
 *   colander_version_info  {}  -> {"name","version","abi"}
 */


#define ABI_VERSION 1

/**
 * `colander_compile`.
 *
 * # Safety
 * `request` must be a valid NUL-terminated UTF-8 C string (or null).
 */
char *colander_compile(const char *request);

/**
 * `colander_free_string`.
 *
 * # Safety
 * See [`free_string`].
 */
void colander_free_string(char *pointer);

/**
 * ABI version, so bindings can fail fast on a mismatch.
 */
uint32_t colander_abi_version(void);

/**
 * `colander_validate_response`.
 *
 * # Safety
 * `request` must be a valid NUL-terminated UTF-8 C string (or null).
 */
char *colander_validate_response(const char *request);

/**
 * `colander_evaluate_rules`.
 *
 * # Safety
 * `request` must be a valid NUL-terminated UTF-8 C string (or null).
 */
char *colander_evaluate_rules(const char *request);

/**
 * `colander_validate_schema`: Draft 2020-12 structural validation.
 *
 * colander ships no schemas, so `schemas` carries the JSON Schema text for
 * whichever document kinds the call needs. `kind: "instance"` is the
 * domain-free entry point: it validates `instanceJson` against `schemaJson`.
 *
 * # Safety
 * `request` must be a valid NUL-terminated UTF-8 C string (or null).
 */
char *colander_validate_schema(const char *request);

/**
 * `colander_content_hash`.
 *
 * # Safety
 * `request` must be a valid NUL-terminated UTF-8 C string (or null).
 */
char *colander_content_hash(const char *request);

/**
 * `colander_next_version`.
 *
 * # Safety
 * `request` must be a valid NUL-terminated UTF-8 C string (or null).
 */
char *colander_next_version(const char *request);

/**
 * `colander_version_info`.
 */
char *colander_version_info(void);

#endif  /* COLANDER_H */
